"""create damage assessments table

Revision ID: 0d6f8b031e7c
Revises: fd8a515f1157
Create Date: 2026-08-15 02:02:32.894094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6f8b031e7c'
down_revision: Union[str, Sequence[str], None] = 'fd8a515f1157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damage_assessments',
    sa.Column('rental_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.Enum('MINOR', 'MODERATE', 'SEVERE', name='damageseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_damage_assessments_rental_id'), 'damage_assessments', ['rental_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_damage_assessments_rental_id'), table_name='damage_assessments')
    op.drop_table('damage_assessments')
    # ### end Alembic commands ###
