"""add_unit_price_to_product_variant

Revision ID: 2660c69cdfe3
Revises: df90aec31c76
Create Date: 2026-08-19 01:36:37.444294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2660c69cdfe3'
down_revision: Union[str, Sequence[str], None] = 'df90aec31c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.execute("UPDATE product_variants SET unit_price = 0.00")
    op.alter_column('product_variants', 'unit_price', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'unit_price')
    # ### end Alembic commands ###
