"""create payments table

Revision ID: 2f27fff810c2
Revises: 0d6f8b031e7c
Create Date: 2026-08-15 14:57:58.982409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f27fff810c2'
down_revision: Union[str, Sequence[str], None] = '0d6f8b031e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('rental_id', sa.Uuid(), nullable=False),
    sa.Column('payment_type', sa.Enum('RENTAL', 'DEPOSIT', 'DAMAGE_CHARGE', 'REFUND', name='paymenttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stripe_payment_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_payment_type'), 'payments', ['payment_type'], unique=False)
    op.create_index(op.f('ix_payments_rental_id'), 'payments', ['rental_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_stripe_payment_id'), 'payments', ['stripe_payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_stripe_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_rental_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_type'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
