"""create rental tables

Revision ID: 4485552b9b93
Revises: 2bed053de5e2
Create Date: 2026-08-13 03:40:07.734958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4485552b9b93'
down_revision: Union[str, Sequence[str], None] = '2bed053de5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentals',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_PAYMENT', 'CONFIRMED', 'READY_FOR_PICKUP', 'ACTIVE', 'RETURN_PENDING', 'RETURNED', 'OVERDUE', 'CANCELLED', 'COMPLETED', name='rentalstatus'), nullable=False),
    sa.Column('rental_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rentals_status'), 'rentals', ['status'], unique=False)
    op.create_index(op.f('ix_rentals_user_id'), 'rentals', ['user_id'], unique=False)
    op.create_table('rental_items',
    sa.Column('rental_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_items_rental_id'), 'rental_items', ['rental_id'], unique=False)
    op.create_index(op.f('ix_rental_items_variant_id'), 'rental_items', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_items_variant_id'), table_name='rental_items')
    op.drop_index(op.f('ix_rental_items_rental_id'), table_name='rental_items')
    op.drop_table('rental_items')
    op.drop_index(op.f('ix_rentals_user_id'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_status'), table_name='rentals')
    op.drop_table('rentals')
    # ### end Alembic commands ###
