"""create inventory allocations

Revision ID: 615fded202a1
Revises: 4485552b9b93
Create Date: 2026-08-13 03:42:31.446427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615fded202a1'
down_revision: Union[str, Sequence[str], None] = '4485552b9b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_allocations',
    sa.Column('inventory_item_id', sa.Uuid(), nullable=False),
    sa.Column('rental_id', sa.Uuid(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_allocations_inventory_item_id'), 'inventory_allocations', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_allocations_rental_id'), 'inventory_allocations', ['rental_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_allocations_rental_id'), table_name='inventory_allocations')
    op.drop_index(op.f('ix_inventory_allocations_inventory_item_id'), table_name='inventory_allocations')
    op.drop_table('inventory_allocations')
    # ### end Alembic commands ###
