"""create inventory items table

Revision ID: f67cb7f40b1e
Revises: fcd15661581f
Create Date: 2026-08-13 03:27:09.574387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67cb7f40b1e'
down_revision: Union[str, Sequence[str], None] = 'fcd15661581f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('asset_code', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'RENTED', 'RESERVED', 'MAINTENANCE', 'LOST', 'RETIRED', name='inventorystatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_inventory_items_asset_code'), 'inventory_items', ['asset_code'], unique=True)
    op.create_index(op.f('ix_inventory_items_status'), 'inventory_items', ['status'], unique=False)
    op.create_index(op.f('ix_inventory_items_variant_id'), 'inventory_items', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_items_variant_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_status'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_asset_code'), table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
