"""create return inspections table

Revision ID: fd8a515f1157
Revises: 615fded202a1
Create Date: 2026-08-15 00:07:14.628423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8a515f1157'
down_revision: Union[str, Sequence[str], None] = '615fded202a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_inspections',
    sa.Column('rental_id', sa.Uuid(), nullable=False),
    sa.Column('condition', sa.Enum('GOOD', 'DAMAGED', name='inspectioncondition'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_inspections_rental_id'), 'return_inspections', ['rental_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_return_inspections_rental_id'), table_name='return_inspections')
    op.drop_table('return_inspections')
    # ### end Alembic commands ###
